apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
      tag: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        resources:
{{ toYaml .Values.resources | indent 12 }}
      ports:
          - containerPort: {{ .Values.containerPort }}
            protocol: TCP
      livenessProbe:
           httpGet:
             path: {{ toYaml .Values.livenessProbe | indent 12 }}
             port: {{ .Values.containerPort }}
           initialDelaySeconds: 3
           periodSeconds: 3
      readinessProbe:
           httpGet:
             path: {{ toYaml .Values.readinessProbe | indent 12 }}
             port: {{ .Values.containerPort }}
           initialDelaySeconds: 3
           periodSeconds: 3
